# Generated by Django 4.2.5 on 2023-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tarif_level',
            field=models.IntegerField(default=0),
        ),
    ]
