# Generated by Django 4.2.5 on 2023-10-20 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_tarif_level_profile_tariff_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storage')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tariff_exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tariff_level',
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_id',
            field=models.UUIDField(default=uuid.UUID('12079778-1b7e-42fa-8dea-2893d0b8fa70')),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_level', models.IntegerField(blank=True, default=None, null=True)),
                ('tariff_exp', models.DateField(blank=True, default=None, null=True)),
                ('volume', models.IntegerField(blank=True, default=0, null=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(to='users.file')),
                ('members', models.ManyToManyField(related_name='group_member', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='group_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
