# Generated by Django 5.0.1 on 2024-01-22 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Create'), ('EDT', 'Edit'), ('DEL', 'Delete')], max_length=3)),
                ('datestamp', models.DateTimeField()),
                ('comment', models.CharField(max_length=60)),
                ('file', models.ManyToManyField(to='users.file', verbose_name='file_id')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
